sonar.projectKey=SonarQube2137
sonar.projectName=Audiovault
sonar.host.url=http://192.168.178.22:9000
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

# Główne ustawienia modułów
sonar.modules=backend,frontend

# --- BACKEND MODULE ---
backend.sonar.projectName=Audiovault Backend
backend.sonar.projectBaseDir=backend
backend.sonar.sources=app
backend.sonar.tests=tests
backend.sonar.python.version=3.10
backend.sonar.python.coverage.reportPaths=coverage.xml
backend.sonar.python.xunit.reportPath=report.xml

# Wykluczenia backendowe - standardowe foldery cache i venv
backend.sonar.exclusions=**/__pycache__/**, **/*.pyc, .venv/**, .pytest_cache/**, **/migrations/**

# --- FRONTEND MODULE ---
frontend.sonar.projectName=Audiovault Frontend
frontend.sonar.projectBaseDir=frontend
frontend.sonar.sources=src
frontend.sonar.tests=src

# Wskazanie, które pliki w 'sources' są tak naprawdę testami
frontend.sonar.test.inclusions=**/*.test.tsx,**/*.spec.tsx,**/*.test.ts,**/*.spec.ts
frontend.sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.tsx,**/*.spec.tsx,**/*.test.ts,**/*.spec.ts,**/vite-env.d.ts

# Raporty pokrycia dla JS/TS
frontend.sonar.javascript.lcov.reportPaths=coverage/lcov.info
frontend.sonar.typescript.lcov.reportPaths=coverage/lcov.info
