
sonar.projectKey=wGw5IVollwIntP9LQXcADdd7v
sonar.projectName=Audiovoult
sonar.projectVersion=1.0
sonar.host.url=http://192.168.178.22:9000
sonar.token=sqp_969e444181fafe6f3bf5b7d075859a353ba48562
sonar.sourceEncoding=UTF-8

# Skanuj cały kod (będzie szukać .ts i .py plików)
sonar.sources=.

# Wykluczenia
sonar.exclusions=node_modules/**,dist/**,.vscode/**,.github/**,.pytest_cache/**,.git/**,coverage/**,*.spec.ts,*.test.ts,*.test.py,**/__pycache__/**

# Łącze do SonarLint dla TypeScript
sonar.typescript.lintJson.reportPaths=eslint-report.json
sonar.issuesReport.html.enable=true
sonar.issuesReport.html.location=./sonar-reports