"""Add Artist and Album models

Revision ID: fc0ebd8b67a8
Revises:
Create Date: 2025-12-07 22:50:44.974602

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc0ebd8b67a8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tracks", sa.Column("artist_id", sa.Uuid(), nullable=True))
    op.add_column("tracks", sa.Column("album_id", sa.Uuid(), nullable=True))
    op.alter_column(
        "tracks", "artist", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    op.create_foreign_key(None, "tracks", "artists", ["artist_id"], ["id"])
    op.create_foreign_key(None, "tracks", "albums", ["album_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tracks", type_="foreignkey")
    op.drop_constraint(None, "tracks", type_="foreignkey")
    op.alter_column(
        "tracks", "artist", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    op.drop_column("tracks", "album_id")
    op.drop_column("tracks", "artist_id")
    # ### end Alembic commands ###
