"""Add Artist and Album models

Revision ID: fc0ebd8b67a8
Revises:
Create Date: 2025-12-07 22:50:44.974602

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc0ebd8b67a8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Use IF NOT EXISTS to make this migration idempotent.
    # The DB may have been initialized via create_all before Alembic tracking was in place,
    # so artist_id/album_id may already exist.
    op.execute("ALTER TABLE tracks ADD COLUMN IF NOT EXISTS artist_id UUID")
    op.execute("ALTER TABLE tracks ADD COLUMN IF NOT EXISTS album_id UUID")
    # DROP NOT NULL is idempotent in PostgreSQL — safe to run even if already nullable.
    op.execute("ALTER TABLE tracks ALTER COLUMN artist DROP NOT NULL")

    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_fk_tables = {fk["referred_table"] for fk in inspector.get_foreign_keys("tracks")}

    if "artists" not in existing_fk_tables:
        op.create_foreign_key("tracks_artist_id_fkey", "tracks", "artists", ["artist_id"], ["id"])
    if "albums" not in existing_fk_tables:
        op.create_foreign_key("tracks_album_id_fkey", "tracks", "albums", ["album_id"], ["id"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tracks_artist_id_fkey", "tracks", type_="foreignkey")
    op.drop_constraint("tracks_album_id_fkey", "tracks", type_="foreignkey")
    op.alter_column("tracks", "artist", existing_type=sa.VARCHAR(length=500), nullable=False)
    op.drop_column("tracks", "album_id")
    op.drop_column("tracks", "artist_id")
    # ### end Alembic commands ###
