"""add_auto_sync_deletions_to_watchlist

Revision ID: 1f61e95eab95
Revises: 89ac9d52b725
Create Date: 2026-06-11 07:46:44.045024

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f61e95eab95"
down_revision: str | None = "89ac9d52b725"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "watchlist", sa.Column("auto_sync_deletions", sa.Boolean(), nullable=False, server_default=sa.text("false"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("watchlist", "auto_sync_deletions")
    # ### end Alembic commands ###
