"""add_compound_indexes

Revision ID: f04ea8a8a02c
Revises: b2c3d4e5f6g7
Create Date: 2026-01-21 15:46:01.251041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04ea8a8a02c'
down_revision: Union[str, None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_listening_history_user_played', 'listening_history', ['user_id', 'played_at'], unique=False)
    op.create_index('ix_playlist_tracks_order', 'playlist_tracks', ['playlist_id', 'order'], unique=False)
    op.create_index('ix_playlists_owner_name', 'playlists', ['owner_id', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_playlists_owner_name', table_name='playlists')
    op.drop_index('ix_playlist_tracks_order', table_name='playlist_tracks')
    op.drop_index('ix_listening_history_user_played', table_name='listening_history')
    # ### end Alembic commands ###
