"""Add Last.fm fields

Revision ID: 9a29c315ce94
Revises: 9e4257a0e6ff
Create Date: 2026-02-03 13:43:47.391554

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a29c315ce94"
down_revision: Union[str, None] = "9e4257a0e6ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("spotify_id", sa.String(length=100), nullable=True),
        sa.Column("deezer_id", sa.String(length=100), nullable=True),
        sa.Column("images", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deezer_id"),
        sa.UniqueConstraint("spotify_id"),
    )
    op.create_index(op.f("ix_artists_name"), "artists", ["name"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("subsonic_password", sa.String(length=100), nullable=True),
        sa.Column("subsonic_salt", sa.String(length=100), nullable=True),
        sa.Column("lastfm_session_key", sa.String(length=255), nullable=True),
        sa.Column("lastfm_username", sa.String(length=100), nullable=True),
        sa.Column("lastfm_connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("preferences", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "albums",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("release_date", sa.String(length=50), nullable=True),
        sa.Column("total_tracks", sa.Integer(), nullable=True),
        sa.Column("artist_id", sa.Uuid(), nullable=True),
        sa.Column("spotify_id", sa.String(length=100), nullable=True),
        sa.Column("deezer_id", sa.String(length=100), nullable=True),
        sa.Column("images", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deezer_id"),
        sa.UniqueConstraint("spotify_id"),
    )
    op.create_index(op.f("ix_albums_title"), "albums", ["title"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("endpoint", sa.String(length=255), nullable=True),
        sa.Column("method", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index("ix_audit_logs_resource", "audit_logs", ["resource_type", "resource_id"], unique=False)
    op.create_index("ix_audit_logs_user_created", "audit_logs", ["user_id", "created_at"], unique=False)
    op.create_table(
        "playlists",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("public", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_playlists_name"), "playlists", ["name"], unique=False)
    op.create_index("ix_playlists_owner_name", "playlists", ["owner_id", "name"], unique=False)
    op.create_table(
        "service_credentials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("service", sa.String(length=50), nullable=True),
        sa.Column("access_token", sa.String(length=2000), nullable=True),
        sa.Column("refresh_token", sa.String(length=2000), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_service_credentials_user_id"), "service_credentials", ["user_id"], unique=False)
    op.create_table(
        "starred_artists",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("artist_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "artist_id", name="unique_starred_artist"),
    )
    op.create_index(op.f("ix_starred_artists_artist_id"), "starred_artists", ["artist_id"], unique=False)
    op.create_index(op.f("ix_starred_artists_user_id"), "starred_artists", ["user_id"], unique=False)
    op.create_table(
        "subsonic_auth_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("salt", sa.String(length=32), nullable=False),
        sa.Column("client_name", sa.String(length=100), nullable=True),
        sa.Column("client_version", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index("ix_subsonic_auth_tokens_token", "subsonic_auth_tokens", ["token"], unique=False)
    op.create_index(
        "ix_subsonic_auth_tokens_user_active", "subsonic_auth_tokens", ["user_id", "is_active"], unique=False
    )
    op.create_table(
        "watchlist",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("watch_type", sa.String(length=20), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=True),
        sa.Column("source_id", sa.String(length=100), nullable=True),
        sa.Column("source_name", sa.String(length=255), nullable=True),
        sa.Column("auto_download", sa.Boolean(), nullable=False),
        sa.Column("check_interval_hours", sa.Integer(), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("new_items_count", sa.Integer(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "source_id", "source", name="unique_watch"),
    )
    op.create_index(op.f("ix_watchlist_user_id"), "watchlist", ["user_id"], unique=False)
    op.create_table(
        "playlist_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("playlist_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("tracks_snapshot", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("change_type", sa.String(length=50), nullable=False),
        sa.Column("change_details", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlists.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_playlist_versions_playlist_created", "playlist_versions", ["playlist_id", "created_at"], unique=False
    )
    op.create_table(
        "starred_albums",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("album_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["albums.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "album_id", name="unique_starred_album"),
    )
    op.create_index(op.f("ix_starred_albums_album_id"), "starred_albums", ["album_id"], unique=False)
    op.create_index(op.f("ix_starred_albums_user_id"), "starred_albums", ["user_id"], unique=False)
    op.create_table(
        "tracks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("artist", sa.String(length=500), nullable=True),
        sa.Column("album", sa.String(length=500), nullable=True),
        sa.Column("artist_id", sa.Uuid(), nullable=True),
        sa.Column("album_id", sa.Uuid(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("isrc", sa.String(length=20), nullable=True),
        sa.Column("spotify_id", sa.String(length=100), nullable=True),
        sa.Column("youtube_id", sa.String(length=100), nullable=True),
        sa.Column("deezer_id", sa.String(length=100), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["albums.id"],
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deezer_id"),
        sa.UniqueConstraint("isrc"),
        sa.UniqueConstraint("spotify_id"),
        sa.UniqueConstraint("youtube_id"),
    )
    op.create_index(op.f("ix_tracks_artist"), "tracks", ["artist"], unique=False)
    op.create_index(op.f("ix_tracks_title"), "tracks", ["title"], unique=False)
    op.create_table(
        "downloads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("track_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=True),
        sa.Column("playlist_name", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_downloads_user_id"), "downloads", ["user_id"], unique=False)
    op.create_table(
        "listening_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("track_id", sa.Uuid(), nullable=True),
        sa.Column("played_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_played", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_listening_history_user_id"), "listening_history", ["user_id"], unique=False)
    op.create_index("ix_listening_history_user_played", "listening_history", ["user_id", "played_at"], unique=False)
    op.create_table(
        "playlist_tracks",
        sa.Column("playlist_id", sa.Uuid(), nullable=False),
        sa.Column("track_id", sa.Uuid(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("playlist_id", "track_id"),
    )
    op.create_index("ix_playlist_tracks_order", "playlist_tracks", ["playlist_id", "order"], unique=False)
    op.create_table(
        "starred_tracks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("track_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "track_id", name="unique_starred_track"),
    )
    op.create_index(op.f("ix_starred_tracks_track_id"), "starred_tracks", ["track_id"], unique=False)
    op.create_index(op.f("ix_starred_tracks_user_id"), "starred_tracks", ["user_id"], unique=False)
    op.create_table(
        "subsonic_now_playing",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("track_id", sa.Uuid(), nullable=False),
        sa.Column("client_name", sa.String(length=100), nullable=True),
        sa.Column("player_id", sa.String(length=100), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("position_seconds", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_subsonic_now_playing_updated", "subsonic_now_playing", ["updated_at"], unique=False)
    op.create_index("ix_subsonic_now_playing_user", "subsonic_now_playing", ["user_id"], unique=False)
    op.create_table(
        "subsonic_ratings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("track_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("rated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_subsonic_ratings_user_track", "subsonic_ratings", ["user_id", "track_id"], unique=True)
    op.create_table(
        "watchlist_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("watchlist_id", sa.Uuid(), nullable=False),
        sa.Column("track_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["watchlist_id"],
            ["watchlist.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("watchlist_id", "track_id", name="unique_watchlist_track"),
    )
    op.create_index(op.f("ix_watchlist_items_track_id"), "watchlist_items", ["track_id"], unique=False)
    op.create_index(op.f("ix_watchlist_items_watchlist_id"), "watchlist_items", ["watchlist_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_watchlist_items_watchlist_id"), table_name="watchlist_items")
    op.drop_index(op.f("ix_watchlist_items_track_id"), table_name="watchlist_items")
    op.drop_table("watchlist_items")
    op.drop_index("ix_subsonic_ratings_user_track", table_name="subsonic_ratings")
    op.drop_table("subsonic_ratings")
    op.drop_index("ix_subsonic_now_playing_user", table_name="subsonic_now_playing")
    op.drop_index("ix_subsonic_now_playing_updated", table_name="subsonic_now_playing")
    op.drop_table("subsonic_now_playing")
    op.drop_index(op.f("ix_starred_tracks_user_id"), table_name="starred_tracks")
    op.drop_index(op.f("ix_starred_tracks_track_id"), table_name="starred_tracks")
    op.drop_table("starred_tracks")
    op.drop_index("ix_playlist_tracks_order", table_name="playlist_tracks")
    op.drop_table("playlist_tracks")
    op.drop_index("ix_listening_history_user_played", table_name="listening_history")
    op.drop_index(op.f("ix_listening_history_user_id"), table_name="listening_history")
    op.drop_table("listening_history")
    op.drop_index(op.f("ix_downloads_user_id"), table_name="downloads")
    op.drop_table("downloads")
    op.drop_index(op.f("ix_tracks_title"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_artist"), table_name="tracks")
    op.drop_table("tracks")
    op.drop_index(op.f("ix_starred_albums_user_id"), table_name="starred_albums")
    op.drop_index(op.f("ix_starred_albums_album_id"), table_name="starred_albums")
    op.drop_table("starred_albums")
    op.drop_index("ix_playlist_versions_playlist_created", table_name="playlist_versions")
    op.drop_table("playlist_versions")
    op.drop_index(op.f("ix_watchlist_user_id"), table_name="watchlist")
    op.drop_table("watchlist")
    op.drop_index("ix_subsonic_auth_tokens_user_active", table_name="subsonic_auth_tokens")
    op.drop_index("ix_subsonic_auth_tokens_token", table_name="subsonic_auth_tokens")
    op.drop_table("subsonic_auth_tokens")
    op.drop_index(op.f("ix_starred_artists_user_id"), table_name="starred_artists")
    op.drop_index(op.f("ix_starred_artists_artist_id"), table_name="starred_artists")
    op.drop_table("starred_artists")
    op.drop_index(op.f("ix_service_credentials_user_id"), table_name="service_credentials")
    op.drop_table("service_credentials")
    op.drop_index("ix_playlists_owner_name", table_name="playlists")
    op.drop_index(op.f("ix_playlists_name"), table_name="playlists")
    op.drop_table("playlists")
    op.drop_index("ix_audit_logs_user_created", table_name="audit_logs")
    op.drop_index("ix_audit_logs_resource", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_albums_title"), table_name="albums")
    op.drop_table("albums")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_artists_name"), table_name="artists")
    op.drop_table("artists")
    # ### end Alembic commands ###
