"""add playlists

Revision ID: a1b2c3d4e5f6
Revises: fc0ebd8b67a8
Create Date: 2026-01-07 00:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a1b2c3d4e5f6"
down_revision = "fc0ebd8b67a8"
branch_labels = None
depends_on = None


def upgrade():
    # Use inspector to make this migration idempotent — tables may already exist
    # if the DB was initialized via create_all before Alembic tracking was in place.
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = set(inspector.get_table_names())

    if "playlists" not in existing_tables:
        op.create_table(
            "playlists",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("name", sa.String(), nullable=False),
            sa.Column("comment", sa.String(), nullable=True),
            sa.Column("owner_id", sa.Uuid(), nullable=False),
            sa.Column("public", sa.Boolean(), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(
                ["owner_id"],
                ["users.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )

    existing_indexes = {idx["name"] for idx in inspector.get_indexes("playlists")} if "playlists" in existing_tables else set()
    if "ix_playlists_id" not in existing_indexes:
        op.create_index(op.f("ix_playlists_id"), "playlists", ["id"], unique=False)
    if "ix_playlists_name" not in existing_indexes:
        op.create_index(op.f("ix_playlists_name"), "playlists", ["name"], unique=False)

    if "playlist_tracks" not in existing_tables:
        op.create_table(
            "playlist_tracks",
            sa.Column("playlist_id", sa.Uuid(), nullable=False),
            sa.Column("track_id", sa.Uuid(), nullable=False),
            sa.Column("order", sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(
                ["playlist_id"],
                ["playlists.id"],
            ),
            sa.ForeignKeyConstraint(
                ["track_id"],
                ["tracks.id"],
            ),
            sa.PrimaryKeyConstraint("playlist_id", "track_id"),
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_table("playlist_tracks")
    op.drop_index(op.f("ix_playlists_name"), table_name="playlists")
    op.drop_index(op.f("ix_playlists_id"), table_name="playlists")
    op.drop_table("playlists")
    # ### end Alembic commands ###
