"""add auto_sync_deletions to watchlist

Revision ID: 89ac9d52b725
Revises: b3f8c9d0e1a2
Create Date: 2026-06-10 11:51:35.801748

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "89ac9d52b725"
down_revision: str | None = "b3f8c9d0e1a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
