"""add_playlist_id_to_downloads

Revision ID: a5d7f8e81880
Revises: 9a29c315ce94
Create Date: 2026-02-10 22:12:20.231517

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5d7f8e81880"
down_revision: Union[str, None] = "9a29c315ce94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("downloads", sa.Column("playlist_id", sa.Uuid(), nullable=True))
    op.create_foreign_key("fk_downloads_playlist_id_playlists", "downloads", "playlists", ["playlist_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_downloads_playlist_id_playlists", "downloads", type_="foreignkey")
    op.drop_column("downloads", "playlist_id")
    # ### end Alembic commands ###
